name: flutter_distributor
description: A complete tool for packaging and publishing your Flutter apps.
version: 0.3.1
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/flutter_distributor
issue_tracker: https://github.com/leanflutter/flutter_distributor/issues

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  app_package_maker: ^0.3.1
  app_package_publisher: ^0.3.1
  args: ^2.2.0
  dio: ^4.0.4
  flutter_app_builder: ^0.3.1
  flutter_app_packager: ^0.3.1
  flutter_app_publisher: ^0.3.1
  logging: ^1.0.2
  path: ^1.8.1
  pubspec_parse: ^1.1.0
  shell_executor: ^0.1.2
  shell_uikit: ^0.1.0
  yaml: ^3.1.0

dev_dependencies:
  dependency_validator: ^3.0.0

executables:
  flutter_distributor: main
