name: app_package_parser
description: App package parser
version: 0.2.3
homepage: https://distributor.leanflutter.org
repository: https://github.com/leanflutter/flutter_distributor/tree/main/packages/app_package_parser

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^3.0.0
